H5Zzfp.c

Not doing so may leave parameter bits unwritten. Many thanks to Peter Lindstrom (@lindstro) for finding this bug.
Closes #1

Flush stream after writing ZFP header

---

H5Zzfp.c

As discussed over e-mail, the first element is the slowest varying HDF5 dataspace dimension, so the order of the arguments to `zfp_field_2d/3d` should be reversed.

Fix array dimension order in zfp_field_* calls

---

src/Makefile

Added wild card specification for installation of the Fortran module 
file instead of the actual name, which can have a different upper/lower case naming convention.

Fix for fortran module install

---

test/Makefile

`make check` fails if we cut out the default `LD_LIBRARY_PATH`, e.g., `libgfortran.so` & friends are not found.

Fix 'make check' failure.

---

src/Makefile

Small update to add GNU Make [DESTDIR](https://www.gnu.org/prep/standards/html_node/DESTDIR.html) support.
This is primarily to facilitate this package's use within python packages.

adding GNU Make DESTDIR support

---

src/H5Zzfp.c

the later is ensured to be properly initialized by HDF5

replace H5E_ERR_CLS_g with H5E_ERR_CLS

---

docs/conf.py
docs/hdf5_chunking.rst
docs/interfaces.rst
src/H5Zzfp.c
test/Makefile
test/test_write.c

- Added an example of a 6D dataset
- A time-varying 3x3 tensor field defined over a 3D spatial domain
- 3 spatial dimensions, 1 time dimension, 2 _value_ dimensions
- Time dimension is _extendible_
- Uses ZFP to compress 4D including the time dimension
- Added documentation about chunking issues

Test and Docs update for ZFP 0.5.4

---

src/H5Zzfp.c

To support testing with ZFP 0.5.5 before it was released, I hacked the main filter code and forgot about it. This update removes that hack

remove #warning and 0x0055 version hack

---

.travis.yml
src/H5Zzfp_props.h

The prop functions cannot really ever be used in the absence of an `hdf5.h` header file. And, I don't want using them to inadvertently include `hdf5.h` for someone if they were not expecting it. So, I've removed it. here.

Remove include for HDF5 header file

---

.github/workflows/main.yml
Makefile
config.make
test/Makefile
test/test_rw_fortran.F90

Search for hdf5 and zfp  in lib64 instead of lib if lib is not present (SuSE builds)
Also, zfp master is using ZFP_BIT_STREAM_WORD_SIZE instead of BIT_STREAM_WORD_TYPE, so that might need to be documented and the error code message updated in the future.
ZFP_BIT_STREAM_WORD_SIZE=8

find zfp and hdf5 in lib64 instead of lib

---

test/test_error.c
test/test_write.c

Happened to see this in GHA logs (thanks to @brtnfld ;) So fixing it here.

Add missing headers for string functions and fix printfs for cd_nelmts

---

.github/workflows/main.yml
config.make
docs/installation.rst
src/H5Zzfp.c

Superscedes #78 by removing use of `ZFP_VERSION_STR` all together.

Use ZFP's version string

---

test/Makefile

- Added the missing $(CFLAGS) in the link step of various
tests. This is particular useful when zfp has been with openMP
support such one can easily add the openMP flag.
- Improved the clean target of the tests. Now it also removes
the file test_zfp_errors.h5

Tests: (fix) Makefile - CFLAGS and clean target

---

src/CMakeLists.txt

- Added the missing header file "H5Zzfp_version.h" to the
h5z_zfp_headers list such it be will installed.

CMake: (fix) Missing header file.

---

src/H5Zzfp.c

It seems Visual Studio compiler has troubles with continuation lines in the middle of macros.
```
H5Zzfp.c
src/H5Z-ZFP/src\H5Zzfp.c(196): error C2121: '#': invalid character: possibly the result of a macro expansion
src/H5Z-ZFP/src\H5Zzfp.c(196): error C2059: syntax error: 'if'
src/H5Z-ZFP/src\H5Zzfp.c(197): fatal error C1019: unexpected #else
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

Compatibility with Visual Studio 2019

---

test/Makefile

Hello, and thank you for H5Z-ZFP.
When packaging it for Debian I noticed that the test suite fails when a test is skipped (ZFP in Debain is currently compiled without CFP), and I assume that was not the intention.
This PR should make it so that the test suite reports failure when a test fails, but not when a test is skipped.

Don't fail the test suite when a test is skipped

---

CMakeLists.txt

- The other day the HDF group has release HDF5 1.14.0. If the MPI parallel version of HDF5 1.14.0 is built using CMake then target MPI::MPI_C is required when using the target ${HDF5_LIBRARIES} in a CMake project like H5Z-ZFP. I have implemented finding the required MPI target in the case if HDF5 is parallel.

CMake: (fix) MPI parallel HDF5 1.14.0

---

.github/workflows/main.yml
CMakeLists.txt

CMake: (fix) parallel HDF5 1.14.0 and MPI
- The other day, the HDF group fixed a small mistake in their
generation of the HDF5 CMake configuration file which solves
the missing target MPI::MPI_C. This fixed will be part
of future versions of HDF5 (1.8, 1.10, 1.12 and 1.14). As a
result we only need to call find_package(MPI) for HDF5
1.14.0 version.
Actions: (fix) apt-get update
- Call apt-get update to ensure we get the latest version
of the latest packages.

Bugfix/hdf5 1.14.0

---

src/H5Zzfp.c

When reading a byte-swapped file, the input is grouped to 4-byte words and each of them is swapped individually. When we try to read such a file, we first validate its header using zfp_read_header with the ZFP_HEADER_MAGIC flag. This flag causes it to only validate the first word to be "zfp\x05". If it is not exactly that, it gives up. Unfortunately, this magic word can already be swapped. The actual byte swapping code would only be tried once the full header would fail to read, so automatic byte swapping never worked.
Instead, when encountering a header with bad magic, try swapping it already and only try reading the full header once the magic (normal or swapped) has been read successfully.
Thanks to Mark C. Miller, Peter Lindstrom and Enrico Zini for doing most of the debugging to get …

fix reading of byte-swapped input files (#95)

---

config.make
test/Makefile

This fixes h5repack test for any endian machine.
Resolves #100
* Adds `-n` (use native types) to `h5repack`
* Uses output from `print_h5repack_farg` to generate argument to `h5repack` test
* Add logic to disallow and print error message if using relative paths for `ZFP_HOME` or `HDF5_HOME` in vanilla gnu make builds

Fix h5repack test

---

src/CMakeLists.txt
test/CMakeLists.txt
test/test_error.c
test/test_read.c
test/test_write.c

- Define _GNU_SOURCE only if it is not defined yet.
- Properly support building of the library and plugin using Microsoft Visual Studio.
- Exclude certain tests when the compiler corresponds to some version of Microsoft Visual Compiler.

Tests: (fix) Small improvements and Github actions

---

config.make
src/H5Zzfp_plugin.h
src/H5Zzfp_props.c
test/test_write.c

- This update fixes a leak of property data when the filter is used as a library (instead of a plugin)
- This also adjusts the generic interface (CPP macros) to set a value of 0 instead of -1 when getting rate, precision or accuracy from a `cd_vals` array to make it consistent with ZFP C API.
- Also fixed a bug in generic interface in `5Pget_zfp_precision_cdata` which set incorrect mode
- Also fixed a UMR bug in generic interface when printing `cd_vals`...an *unused* value was not set and so printing the array of `cd_vals` resulted in printing uninitialized memory. Maybe this was happening on Windows...but it would only show up during tests of `test_write_plugin` as that is only executable using generic interface.
- Made gnumake warn instead of error if no `zfp.h` found so that `make …

Fix leak and consistify generic API with ZFP C API

---

.github/workflows/codespell.yml
.github/workflows/main.yml
config.make
src/H5Zzfp.c
test/Makefile
test/test_common.h
test/test_error.c
test/test_write.c

* Reworked the strndup function used for Windows testing.
- Reran the action multiple times, and it has never failed the Windows tests, thus far.
* Added a spell checker and fix some spelling errors
* Updated the Windows HDF5 CI version to 1.14.5

Windows CI testing and spelling fixes
